Repository katspaugh/wavesurfer.js, pull requests merged in 2019-12, with the labels that each got.

#1823 regions plugin: don't assign to module object
  src/plugin/regions.js
Labels: plugins

#1798 regions plugin: allow setting the handleColor inside addRegion
  src/plugin/regions.js
Labels: enhancement, needs-update, plugins

#1824 methods.html: typo fix
  docs/methods.html
Labels: documentation, website

#1829 regions plugin: add option to select specific channel to draw on
  src/plugin/regions.js
Labels: enhancement, plugins

#1828 regions plugin: disable drag selection before enabling it
  src/plugin/regions.js
Labels: plugins

#1831 update docs for v3.3.0
  docs/methods.html
  docs/options.html
Labels: website

#1835 release v3.3.0
  CHANGES.md
  LICENSE
  bower.json
  package.json
Labels: release
