Repository katspaugh/wavesurfer.js, pull requests merged in 2019-07, with the labels that each got.

#1541 replace usage of util.ajax with util.fetchFile
  .eslintrc.js
  CHANGES.md
  example/annotation/app.js
  example/audio-element/main.js
  example/cursor/main.js
  example/elan/app.js
  example/microphone/app.js
  example/minimap/app.js
  example/mute/app.js
  example/playlist/app.js
  example/regions/app.js
  example/rtl/main.js
  example/spectrogram/app.js
  example/split-channels/app.js
  example/timeline-notches/main.js
  example/video-element/main.js
  example/zoom/main.js
  karma.conf.js
  package.json
  spec/support/test.json
  spec/support/test.txt
  spec/test-helpers.js
  spec/util.spec.js
  spec/wavesurfer.spec.js
  src/html-init.js
  src/util/ajax.js
  src/util/fetch.js
  src/util/index.js
  src/wavesurfer.js
Labels: enhancement

#1685 tests: add coverage for wavesurfer.cancelAjax
  package.json
  spec/wavesurfer.spec.js
  src/wavesurfer.js
Labels: tests

#1687 docs: add upgrade instructions for 3.0
  CHANGES.md
  UPGRADE.md
Labels: documentation

#1688 release 3.0.0
  CHANGES.md
  bower.json
  package.json
Labels: release
