Repository katspaugh/wavesurfer.js, pull requests merged in 2019-05, with the labels that each got.

#1638 Fix comparison of seconds and getDuration in setCurrentTime
  src/wavesurfer.js
Labels: needs-update

#1646 plugins: remove deprecated static methods
  CHANGES.md
  src/plugin/cursor.js
  src/plugin/minimap.js
  src/plugin/regions.js
Labels: plugins

#1647 doc: add missing and fix invalid jsdoc statements
  .eslintrc.js
  src/drawer.canvasentry.js
  src/drawer.js
  src/drawer.multicanvas.js
  src/mediaelement.js
  src/peakcache.js
  src/plugin/cursor.js
  src/plugin/microphone.js
  src/plugin/regions.js
  src/plugin/timeline.js
  src/util/get-id.js
  src/util/observer.js
  src/util/prevent-click.js
  src/util/request-animation-frame.js
  src/wavesurfer.js
  src/webaudio.js
Labels: documentation

#1654 spectrogram plugin: allow user to specify a colorMap
  CHANGES.md
  example/spectrogram/app.js
  example/spectrogram/hot-colormap.json
  example/spectrogram/index.html
  src/plugin/spectrogram.js
Labels: plugins

#1658 improve documentation for util.ajax
  CHANGES.md
  src/util/ajax.js
  src/wavesurfer.js
Labels: documentation
