Repository katspaugh/wavesurfer.js, pull requests merged in 2019-03, with the labels that each got.

#1581 spectrogram plugin: properly remove event listeners
  CHANGES.md
  package.json
  src/plugin/spectrogram.js
Labels: plugins

#1441 regions plugin: display regions before file load
  src/plugin/regions.js
  src/wavesurfer.js
  src/webaudio.js
Labels: enhancement, plugins

#1593 spectrogram plugin: fix event listeners
  CHANGES.md
  src/plugin/spectrogram.js
Labels: plugins

#1603 add wavesurfer.getActivePlugins()
  CHANGES.md
  spec/plugin-api.spec.js
  src/wavesurfer.js
Labels: enhancement
