Repository katspaugh/wavesurfer.js, pull requests merged in 2019-10, with the labels that each got.

#1762 regions plugin: change position of region end handler
  src/plugin/regions.js
Labels: plugins

#1776 Cursor Plugin: Flip time text to left of cursor on right edge for readability
  CHANGES.md
  src/plugin/cursor.js
Labels: enhancement, plugins

#1767 Allow to use HTML5 audio tag with API Web Audio
  CHANGES.md
  example/media/stereo.mp3
  example/mediaelement-webaudio/app.js
  example/mediaelement-webaudio/index.html
  example/mediaelement-webaudio/stereo-peaks.json
  example/split-channels/app.js
  karma.conf.js
  spec/mediaelement-shared.js
  spec/mediaelement-webaudio.spec.js
  spec/mediaelement.spec.js
  src/mediaelement-webaudio.js
  src/mediaelement.js
  src/wavesurfer.js
  src/webaudio.js
Labels: enhancement

#1781 style right and left handles of region plugin independently
  src/plugin/regions.js
Labels: plugins

#1782 Update documentation for 3.2.0
  docs/events.html
  docs/methods.html
  docs/options.html
  package.json
Labels: documentation, website

#1783 release: v3.2.0
  CHANGES.md
  bower.json
  package.json
Labels: release

#1789 scale-json.py: limit nr of digits to 2
  faq/index.html
Labels: documentation
