Repository katspaugh/wavesurfer.js, pull requests merged in 2019-04, with the labels that each got.

#1605 cursor plugin: add showTimeYPosition option
  CHANGES.md
  src/plugin/cursor.js
Labels: enhancement, plugins

#1608 regions plugin: fix ready listener when loading multiple audio files
  CHANGES.md
  example/spectrogram/index.html
  src/plugin/regions.js
Labels: plugins

#1560 travis: enable the autoplay policy for Web Audio in Chrome
  .travis.yml
  karma.conf.js
Labels: tests

#1611 add Blob support for exportImage
  CHANGES.md
  package.json
  spec/wavesurfer.spec.js
  src/drawer.multicanvas.js
  src/wavesurfer.js
Labels: enhancement

#1613 timeline plugin: fix ready listener when loading multiple audio files
  CHANGES.md
  src/plugin/timeline.js
Labels: plugins

#1617 refactor: add drawer.canvasentry
  CHANGES.md
  build-config/fragments/common.js
  package.json
  src/drawer.canvasentry.js
  src/drawer.multicanvas.js
Labels: enhancement

#1619 add prefix argument to util.getId
  CHANGES.md
  spec/util.spec.js
  src/drawer.canvasentry.js
  src/util/get-id.js
Labels: enhancement

#1623 timeline plugin: add offset parameter
  example/timeline/index.html
  src/plugin/timeline.js
Labels: plugins

#1633 regions plugin: allow drawing new regions over old ones, when the old ones are not resizable and not draggable
  CHANGES.md
  src/plugin/regions.js
Labels: plugins

#1632 regions plugin: snap to grid options
  CHANGES.md
  src/plugin/regions.js
Labels: enhancement, plugins
