Repository katspaugh/wavesurfer.js, pull requests merged in 2019-09, with the labels that each got.

#1702 add autoCenter option
  src/drawer.js
  src/wavesurfer.js
Labels: enhancement

#1742 spectrogram plugin: fix variable name in click handler
  src/plugin/spectrogram.js
Labels: plugins

#1743 minimap plugin: fix left/width calculations for regions on retina/4k screens
  src/plugin/minimap.js
Labels: plugins

#1751 release: 3.1.0
  CHANGES.md
  bower.json
  package.json
Labels: release
