Repository katspaugh/wavesurfer.js, pull requests merged in 2019-11, with the labels that each got.

#1794 regions plugin: add start argument to play and playLoop methods
  src/plugin/regions.js
Labels: plugins

#1793 regions plugin: add maxRegions option to limit max nr of created regions
  src/plugin/regions.js
Labels: plugins

#1796 docs: remove non-existing method
  docs/methods.html
Labels: documentation

#1809 cursor plugin: fix time visibility
  src/plugin/cursor.js
Labels: plugins

#1812 add drawingContextAttributes option and enable canvas desynchronized hint
  CHANGES.md
  src/drawer.canvasentry.js
  src/drawer.multicanvas.js
  src/wavesurfer.js
Labels: enhancement

#1813 document barMinHeight. Also some css to stop prop names from wrapping.
  docs/options.html
Labels: documentation, website

#1811 return Promise from wavesurfer.exportPCM
  CHANGES.md
  spec/wavesurfer.spec.js
  src/wavesurfer.js
Labels: enhancement
