Repository katspaugh/wavesurfer.js, pull requests merged in 2020-05, with the labels that each got.

#1929 Regions plugin: fix switch loop region
  src/plugin/regions.js
Labels: plugins

#1943 minimap plugin: added ability to use a customized regions plugin
  CHANGES.md
  src/plugin/minimap.js
Labels: plugins

#1949 regions plugin: ability to specify time format using timeformatCallback
  CHANGES.md
  src/plugin/regions/index.js
  src/plugin/regions/region.js
Labels: enhancement, plugins

#1947 When splitting channels, allow coloring and filtering of channels
  CHANGES.md
  example/split-channels/app.js
  example/split-channels/index.html
  src/drawer.multicanvas.js
  src/wavesurfer.js
Labels: enhancement

#1953 minimap plugin: added check for drawer presence
  CHANGES.md
  src/plugin/minimap.js
Labels: plugins
