Repository katspaugh/wavesurfer.js, pull requests merged in 2020-06, with the labels that each got.

#1956 spectrogram plugin: perform null check when removing scroll listener
  src/plugin/spectrogram.js
Labels: plugins

#1974 Release 4.0.0
  CHANGES.md
  bower.json
  package.json
Labels: release

#1978 Improve region example
  example/regions/app.js
  example/regions/index.html
Labels: examples, plugins

#1979 release 4.0.1
  CHANGES.md
  bower.json
  package.json
Labels: release

#1984 Add publishConfig
  package.json
Labels: website

#1977 regions plugin: improve loop playback logic
  CHANGES.md
  src/plugin/regions/region.js
Labels: plugins

#1983 performance: use clip-path css instead of width
  CHANGES.md
  src/drawer.multicanvas.js
Labels: enhancement
