Repository katspaugh/wavesurfer.js, pull requests merged in 2020-09, with the labels that each got.

#2063 Fix for unhandled AbortError thrown during cancelAjax
  CHANGES.md
  src/wavesurfer.js
Labels: tests

#2065 release 4.1.0
  CHANGES.md
  README.md
  bower.json
  package.json
Labels: release

#2071 release: 4.1.1
  CHANGES.md
  bower.json
  package.json
Labels: release

#2045 Fix performance issues with seeking while audio is playing
  CHANGES.md
  src/wavesurfer.js
Labels: performance-question
