Repository katspaugh/wavesurfer.js, pull requests merged in 2020-01, with the labels that each got.

#1839 regions plugin: improve handle style support
  src/plugin/regions.js
Labels: plugins

#1844 regions plugin: add support for a context menu event on a region
  src/plugin/regions.js
Labels: enhancement, needs-update, plugins

#1845 regions plugin: handle position fix while using with channelIdx param
  src/plugin/regions.js
Labels: needs-update, plugins

#1848 release v3.3.1
  CHANGES.md
  bower.json
  package.json
Labels: release

#1851 spectrogram plugin: correct the hamming windfunc formula
  src/plugin/spectrogram.js
Labels: plugins
