Repository katspaugh/wavesurfer.js, pull requests merged in 2020-04, with the labels that each got.

#1916 bump version: v3.3.3
  CHANGES.md
  bower.json
  package.json
Labels: release

#1858 Regions plugin: fix channelCount
  src/plugin/regions.js
Labels: plugins

#1919 Elan plugin: optional params.tiers (#1910)
  src/plugin/elan.js
Labels: plugins

#1921 Plugin inheritance example in 'plugin-system'
  example/plugin-system/app.js
  example/plugin-system/custom-plugin/CursorCustomPlugin.js
  example/plugin-system/index.html
Labels: enhancement, examples
