Repository katspaugh/wavesurfer.js, pull requests merged in 2021-01, with the labels that each got.

#2150 Update to support multi channel colors for bars
  CHANGES.md
  example/bars/index.html
  example/bars/main.js
  src/drawer.multicanvas.js
Labels: enhancement

#2153 release: 4.4.0
  CHANGES.md
  LICENSE
  package.json
Labels: release

#2155 examples: add missing sample.m3u
  example/playlist/sample.m3u
Labels: bug, examples

#2158 regions plugin: stop dragging region when mouse exits wavesurfer div
  CHANGES.md
  src/plugin/regions/index.js
Labels: plugins

#2148 WaveSurfer load() should accept HTMLMediaElement when using WebAudio
  CHANGES.md
  karma.conf.js
  spec/webaudio.spec.js
  src/wavesurfer.js
Labels: bug, needs-update

#2169 Added MediaEdits.io to Commercial List
  projects/index.html
Labels: documentation

#2164 ensure webaudio is removed from ram/cpu usage
  CHANGES.md
  spec/wavesurfer.spec.js
  src/wavesurfer.js
Labels: bug, webaudio

#2173 build: remove publicPath from webpack dev config
  build-config/fragments/dev.js
Labels: build

#2171 microphone plugin: remove deprecated MediaStream.stop call
  CHANGES.md
  src/plugin/microphone/index.js
Labels: plugins
