Repository katspaugh/wavesurfer.js, pull requests merged in 2021-08, with the labels that each got.

#2342 examples: fix sample code in timeline-notches
  example/timeline-notches/index.html
Labels: examples

#2339 regions plugin: add direction and action to region-updated event params
  CHANGES.md
  src/plugin/regions/region.js
Labels: plugins

#2333 timeline plugin: fix null is not an object in fillText
  CHANGES.md
  src/plugin/timeline/index.js
Labels: plugins

#2332 release: v5.2.0
  CHANGES.md
  bower.json
  build-config/fragments/common.js
  package.json
Labels: release

#2343 regions plugin: fix region resize event direction
  src/plugin/regions/region.js
Labels: plugins

#2345 Support for linear gradients: add additional type to waveColor and progressColor parameters
  CHANGES.md
  example/gradient-fill-styles/index.html
  example/gradient-fill-styles/main.js
  spec/wavesurfer.spec.js
  src/drawer.canvasentry.js
  src/wavesurfer.js
Labels: enhancement
