Repository katspaugh/wavesurfer.js, pull requests merged in 2021-04, with the labels that each got.

#2195 Add first-class support for vertical orientation
  .eslintrc.js
  CHANGES.md
  example/css/style.css
  example/vertical/index.html
  example/vertical/main.js
  package.json
  spec/drawer.spec.js
  src/drawer.canvasentry.js
  src/drawer.js
  src/drawer.multicanvas.js
  src/util/index.js
  src/util/orientation.js
  src/wavesurfer.js
Labels: enhancement

#2240 Clarify and restructure upgrade documentation
  _config.yml
  _includes/head.html
  upgrade/v2/changes.html
  upgrade/v2/index.html
  upgrade/v2/upgrading.html
  v2/index.html
  v2/plugin-class.html
Labels: documentation

#2241 Automate GitHub releases
  .github/workflows/publish.yml
Labels: ci, release

#2242 regions plugin: support for vertical orientation
  src/drawer.js
  src/plugin/regions/index.js
  src/plugin/regions/region.js
Labels: enhancement, plugins

#2175 Fix exportPCM noWindow parameter
  CHANGES.md
  package.json
  spec/wavesurfer.spec.js
  src/wavesurfer.js
Labels: bug, enhancement
