Repository katspaugh/wavesurfer.js, pull requests merged in 2021-06, with the labels that each got.

#2293 regions plugin: cursor orientation bugfix
  CHANGES.md
  src/plugin/regions/region.js
Labels: plugins

#2287 markers plugin: trigger click event on wavesurfer
  CHANGES.md
  src/plugin/markers/index.js
Labels: plugins

#2301 examples: fix wrong url path in markers example
  plugins/markers.js
Labels: examples

#2299 plugins: prevent runtime errors when canvas context is null (setFillStyles, setFonts)
  CHANGES.md
  src/plugin/spectrogram/index.js
  src/plugin/timeline/index.js
Labels: plugins

#2252 regions plugin: fix Intervention message on mobile devices
  src/plugin/regions/region.js
Labels: plugins

#2298 markers plugin: custom HTML elements are now centered over the marker line
  CHANGES.md
  example/markers/app.js
  example/markers/settings_icon.png
  src/plugin/markers/index.js
Labels: plugins

#2309 release: 5.1.0
  CHANGES.md
  bower.json
  package.json
Labels: release
