Repository katspaugh/wavesurfer.js, pull requests merged in 2021-03, with the labels that each got.

#2196 Add Markers plugin
  CHANGES.md
  example/annotation/app.js
  example/annotation/index.html
  example/markers/app.js
  example/markers/index.html
  example/trivia.js
  src/plugin/markers/index.js
Labels: plugins

#2201 webaudio: fix decodeAudioData handling in Safari
  CHANGES.md
  src/webaudio.js
Labels: safari-issue

#2202 release: 4.6.0
  CHANGES.md
  bower.json
  package.json
Labels: release

#2208 markers plugin: markers at the begin/end of file were screwing up seeking
  CHANGES.md
  example/markers/app.js
  src/plugin/markers/index.js
Labels: plugins

#2213 regions plugin: drag bugfix & showTooltip parameter
  CHANGES.md
  src/plugin/regions/index.js
  src/plugin/regions/region.js
Labels: plugins

#2205 Publish to NPM via GitHub Actions
  .github/workflows/publish.yml
  README.md
Labels: ci, documentation

#2227 get examples working again
  .eslintrc.js
  example/audio-element/main.js
  example/elan/app.js
  example/equalizer/main.js
  example/main.js
  example/media-session/app.js
  example/minimap/app.js
  example/mute/app.js
  example/panner/main.js
  example/playlist/app.js
  example/plugin-system/app.js
  example/regions/app.js
  example/rtl/main.js
  example/spectrogram/app.js
  example/split-channels/app.js
  example/timeline-notches/main.js
  example/timeline/app.js
  example/trivia.js
  example/video-annotation/main.js
  example/video-element/main.js
  example/zoom/main.js
Labels: examples
