Repository katspaugh/wavesurfer.js, pull requests merged in 2022-03, with the labels that each got.

#2467 release: 6.0.3
  CHANGES.md
  bower.json
  package.json
Labels: release

#2470 timeline plugin: fix negative offset rendering
  CHANGES.md
  src/plugin/timeline/index.js
Labels: plugins

#2471 spectrogram plugin: Add `frequencyMin`, `frequencyMax` scaling option
  CHANGES.md
  example/spectrogram/index.html
  src/plugin/spectrogram/index.js
Labels: plugins

#2474 release: 6.0.4
  CHANGES.md
  bower.json
  package.json
Labels: release

#2477 [DOCUMENTATION] change description of audioprocess event
  docs/events.html
Labels: documentation

#2480 minimap plugin: clear waveform when load new audio
  CHANGES.md
  src/plugin/minimap/index.js
Labels: enhancement, plugins

#2483 minimap plugin: changed regions function name to resolve ambiguities
  CHANGES.md
  src/plugin/minimap/index.js
Labels: plugins
