Repository katspaugh/wavesurfer.js, pull requests merged in 2022-02, with the labels that each got.

#2437 release: 6.0.0
  CHANGES.md
  bower.json
  package.json
Labels: release

#2441 docs: add upgrade instructions for 6.0
  UPGRADE.md
  src/drawer.canvasentry.js
Labels: documentation

#2447 release: 6.0.1
  CHANGES.md
  bower.json
  package.json
Labels: release

#2454 Correct type of maxRegions property of RegionsPlugin
  CHANGES.md
  src/plugin/regions/index.js
Labels: plugins

#2457 release: 6.0.2
  CHANGES.md
  bower.json
  package.json
Labels: release

#2464 cursor plugin: fix doc types for opacity and followCursorY
  CHANGES.md
  src/plugin/cursor/index.js
Labels: plugins, documentation

#2462 cursor plugin: fix element removal in destroy
  CHANGES.md
  src/plugin/cursor/index.js
Labels: plugins
