Repository katspaugh/wavesurfer.js, pull requests merged in 2022-10, with the labels that each got.

#2599 markers plugin: check for event after every add/remove
  CHANGES.md
  src/plugin/markers/index.js
Labels: plugins

#2604 Add drawBuffer method in the documentation
  docs/methods.html
Labels: documentation

#2606 cursor plugin: fix crash when destroy triggered before ready
  CHANGES.md
  src/plugin/cursor/index.js
Labels: plugins, needs-update
