Repository katspaugh/wavesurfer.js, pull requests merged in 2023-03, with the labels that each got.

#2691 Proxy HTMLMediaElement's 'waiting' event through MediaElement backend.
  src/mediaelement.js
Labels: enhancement

#2686 Fix iphone silent switch webaudio mute
  CHANGES.md
  src/util/silence-mode.js
Labels: safari-issue, webaudio

#2700 Docs: add an import snippet
  README.md
Labels: documentation

#2701 Add autoCenterImmediately option in the documentation
  docs/options.html
Labels: documentation

#2704 funding: update the sponsorship account
  .github/FUNDING.yml
Labels: funding

#2664 Markers Plugin: Inherit `font-family` rather than setting `monospace`
  src/plugin/markers/index.js
Labels: plugins

#2521 regions plugin: add editableContent and removeButton options
  CHANGES.md
  example/video-annotation-contentEditable-regions/index.html
  example/video-annotation-contentEditable-regions/main.js
  src/plugin/regions/index.js
  src/plugin/regions/region.js
Labels: enhancement, plugins

#2646 Zoom optimisation for Waves and matching implementation for Spectrograms
  example/spectrogram/app.js
  example/spectrogram/index.html
  example/zoom/index.html
  example/zoom/main.js
  src/drawer.canvasentry.js
  src/drawer.js
  src/drawer.multicanvas.js
  src/plugin/spectrogram/index.js
  src/wavesurfer.js
Labels: enhancement, plugins

#2715 Release 6.6.0
  CHANGES.md
  bower.json
  package.json
Labels: release
